name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          env: testing-pyold

        - os: ubuntu-latest
          env: testing-pynew

        - os: macos-latest
          env: testing

        - os: windows-latest
          env: testing
    env:
      SYMMRAY_DEBUG: "1"

    steps:
    - uses: actions/checkout@v5

    - uses: prefix-dev/setup-pixi@v0.9.1
      with:
        environments: ${{ matrix.env }}

    - name: Test with pytest
      run: |
        pixi run -e ${{ matrix.env }} \
        pytest tests/ \
        --cov=symmray \
        --cov-report=xml \
        --verbose \
        --durations=10

    - name: Report to codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}